manifest:
  remotes:
    - name: LOWPROKB
      url-base: https://github.com/LOWPROKB
    - name: ym-han
      url-base: https://github.com/ym-han
  projects:
    - name: zmk
      remote: ym-han
      revision: zen-on-main+969+plover-hid
      import: app/west.yml
  self:
    path: config